### ISSUE TITLE
[DB] Schedule Table에 Day Of Week 컬럼이 생성되지 않음

### ISSUE THREAD

**Issue by stackzero00** [TIG-Inha/TimeIsGold_Backend#64]
:rage:**오류 설명**
Schedule Table에 Day Of Week 칼럼이 생성되지 않음

---
:mag_right:**오류 발생 상황**
Spring App 실행 시 Schedule Table에 Day Of Week 컬럼이 생성되지 않음. 

---
:grin:**의도한 결과**
App 실행 시 Schedule Table에 Day Of Week 컬럼이 추가되어야 함.
---
:fireworks:**스크린샷**
<img width="598" alt="image" src="https://user-images.githubusercontent.com/111207937/226272636-b4d9ac90-b094-412f-adf2-4c865ef00db5.png">

**Comment by ryulkim** [comment]
확인했습니다.
